//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordxTex.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WordxTex.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Button_About {
            get {
                object obj = ResourceManager.GetObject("Button_About", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Button_Baseline_Down {
            get {
                object obj = ResourceManager.GetObject("Button_Baseline_Down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Button_Baseline_Reset {
            get {
                object obj = ResourceManager.GetObject("Button_Baseline_Reset", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Button_Baseline_Up {
            get {
                object obj = ResourceManager.GetObject("Button_Baseline_Up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Button_Edit {
            get {
                object obj = ResourceManager.GetObject("Button_Edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Button_Insert_Graph {
            get {
                object obj = ResourceManager.GetObject("Button_Insert_Graph", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Button_Insert_MathChemRea {
            get {
                object obj = ResourceManager.GetObject("Button_Insert_MathChemRea", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Button_Insert_MathChemStru {
            get {
                object obj = ResourceManager.GetObject("Button_Insert_MathChemStru", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Button_Insert_MathEQ {
            get {
                object obj = ResourceManager.GetObject("Button_Insert_MathEQ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Button_Insert_Tex {
            get {
                object obj = ResourceManager.GetObject("Button_Insert_Tex", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Button_Settings {
            get {
                object obj = ResourceManager.GetObject("Button_Settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \renewcommand{\normalsize}{\fontsize{%%WordxTex_Font_Symbol}{%%WordxTex_Font_Symbol}\selectfont}
        ///%%WordxTex_Equation_Font_Symbal
        ///\DeclareMathSizes{8}{8}{7}{5}
        ///\DeclareMathSizes{9}{9}{7}{5}
        ///\DeclareMathSizes{10}{10}{8}{5}
        ///\DeclareMathSizes{11}{11}{9}{7}
        ///\DeclareMathSizes{12}{12}{9}{7}
        ///\DeclareMathSizes{14}{14}{10}{7}
        ///\DeclareMathSizes{16}{16}{12}{8}
        ///\DeclareMathSizes{18}{18}{14}{10}
        ///\DeclareMathSizes{20}{20}{16}{12}
        ///\DeclareMathSizes{24}{24}{18}{14}
        ///\DeclareMathSizes{28}{28}{20}{16}
        ///\DeclareMath [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tex_fontsize_style {
            get {
                return ResourceManager.GetString("tex_fontsize_style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %!WordxTex_TexContent DO NOT DELETE THIS LINE
        ///\documentclass{article}
        ///%param.sty a fontsize adjust automatically.
        ///\usepackage{param}
        ///\usepackage{textcomp}
        ///\usepackage[version=4]{mhchem}
        ///\pagestyle{empty}
        ///\normalsize
        ///
        ///\begin{document}
        ///%%sample
        ///%\ce{A + B &lt;=&gt;[HP][LP] C}
        ///\end{document}.
        /// </summary>
        internal static string tex_sample_chemrea {
            get {
                return ResourceManager.GetString("tex_sample_chemrea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %!WordxTex_TexContent DO NOT DELETE THIS LINE
        ///\documentclass{article}
        ///%%param.sty for font adjustment.
        ///\usepackage{param}
        ///\usepackage{chemfig}
        ///\usepackage[active,tightpage]{preview}
        ///\pagestyle{empty}
        ///\renewcommand{\normalsize}{\fontsize{10}{10}\selectfont}
        ///\normalsize
        ///\PreviewEnvironment{tikzpicture}
        ///\setlength\PreviewBorder{0pt}
        ///
        ///\begin{document}
        ///%%sample
        ///%\chemfig{*6(-=-=-=)}
        ///\end{document}.
        /// </summary>
        internal static string tex_sample_chemstr {
            get {
                return ResourceManager.GetString("tex_sample_chemstr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %!WordxTex_TexContent DO NOT DELETE THIS LINE
        ///\documentclass{article}
        ///%%param.sty for font adjustment.
        ///\usepackage{param}
        ///\pagestyle{empty}
        ///\normalsize
        ///
        ///\begin{document}
        ///\[
        ///%%sample
        ///%\int_{x}^{y} \sqrt[3]{\exp(z)}\, \mathrm{d}z
        ///\]
        ///\end{document}.
        /// </summary>
        internal static string tex_sample_matheq {
            get {
                return ResourceManager.GetString("tex_sample_matheq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %!WordxTex_TexContent DO NOT DELETE THIS LINE
        ///\documentclass{article}
        ///%%param.sty for font adjustment.
        ///\usepackage{param}
        ///\usepackage{pgfplots}
        ///\usepackage{pgfplotstable}
        ///\usepackage{mathpazo}
        ///\usepackage{filecontents}
        ///\begin{filecontents*}{0.5atm_ethanal_aq.dat}
        ///L V
        ///0.936 0.94056
        ///0.94 0.943692
        ///0.944 0.946891
        ///0.948 0.950161
        ///0.952 0.953502
        ///0.956 0.956918
        ///0.96 0.960409
        ///0.964 0.963978
        ///0.968 0.967628
        ///0.972 0.97136
        ///0.976 0.975177
        ///0.98 0.979081
        ///\end{filecontents*}
        ///\begin{filecontents*}{1atm [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tex_sample_plot {
            get {
                return ResourceManager.GetString("tex_sample_plot", resourceCulture);
            }
        }
    }
}
